# Generated by Django 4.2.13 on 2024-07-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Корпус')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес корпуса')),
                ('cabinet', models.CharField(max_length=10, verbose_name='Кабинет')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпусы',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Подразделение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_dict_site.subdivision')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=150, verbose_name='ФИО')),
                ('mail', models.EmailField(max_length=100, verbose_name='Почта')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('employeeId', models.CharField(max_length=20, verbose_name='Идентификатор 1С')),
                ('inter_phone', models.CharField(max_length=30, verbose_name='Внутренный телефон')),
                ('ext_phone', models.CharField(max_length=20, verbose_name='Внешний телефон')),
                ('visible', models.BooleanField(verbose_name='Видимость')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone_dict_site.building')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone_dict_site.subdivision')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
